Gravatarfix
emicludo/DevOps-group_s pull request #182
Opened 2023-06-06 13:14 UTC by nikogio

Fixed loading of gravatar images

changed helmet package as a middleware to handle image loading from www.gravatar.com

2023-06-06 16:44 UTC, Matej-Basta requested changes

2023-06-06 16:44 UTC, Matej-Basta commented on itu-minitwit-node/package-lock.json
please, put this into your gitignore and take it away from here. :)

2023-06-06 16:44 UTC, Matej-Basta commented on itu-minitwit-node/src/views/timeline.jade
> +
This is probably not necessary. :D

2023-06-07 06:10 UTC, nikogio commented on itu-minitwit-node/package-lock.json
thanks mate! youll see a brand new pull request created for this

2023-06-07 06:10 UTC, closed without merging

2023-06-07 06:11 UTC, nikogio commented
forgot to stash package lock. created a new pull request